FROM node:16-alpine

ARG NPM_REGISTRY_AUTH_TOKEN
ENV NPM_REGISTRY_AUTH_TOKEN=$NPM_REGISTRY_AUTH_TOKEN

WORKDIR /app

COPY server/package.json .
COPY .npmrc .
RUN yarn && yarn global add nodemon

COPY server .
RUN yarn build

EXPOSE 3000
CMD yarn start
