apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: am.xtianwatch.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uncanon-server
                port:
                  number: 3000
    - host: dam.xtianwatch.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello
                port:
                  number: 3000
