// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const colors = {
 "black": "rgba(77, 51, 51, 1)",
 "white": "rgba(255, 250, 250, 1)",
 "gray1": "rgba(79, 79, 79, 1)",
 "gray2": "rgba(130, 130, 130, 1)",
 "gray3": "rgba(189, 189, 189, 1)",
 "gray4": "rgba(224, 224, 224, 1)",
 "gray5": "rgba(242, 242, 242, 1)",
 "secondarySalmon": "rgba(228, 183, 183, 1)",
 "rosewhite": "rgba(255, 244, 244, 1)"
} as const;

export default colors;