// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontSizes = {
 "h1": "48px",
 "h2": "40px",
 "h3": "32px",
 "h4": "26px",
 "h5": "20px",
 "h6": "18px",
 "paragraph": "16px",
 "sub": "12px"
} as const;

export default fontSizes;