// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontFamilies = {
 "light": "Barlow Semi Condensed",
 "regular": "Barlow Semi Condensed",
 "medium": "Barlow Semi Condensed",
 "bold": "Barlow Semi Condensed"
} as const;

export default fontFamilies;