// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const letterSpacings = {
 "regular": "0px",
 "wide": "0.8px",
 "tight": "-0.72px"
} as const;

export default letterSpacings;