// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const mediaQueries = {
 "desktopMin": "900px",
 "tabletMax": "899px",
 "tabletMin": "768px",
 "mobileMax": "767px",
 "zero": "1px"
} as const;

export default mediaQueries;