// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const spacing = {
 "tiny": "8px",
 "small": "16px",
 "medium": "32px",
 "big": "48px",
 "large": "64px",
 "huge": "96px",
 "cardContent": "80px",
 "shadow": "5px",
 "desktopSortControl": "320px"
} as const;

export default spacing;